name: protest
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_animate: ^4.3.0
  another_flushbar: ^1.12.30
  dio: ^5.4.0
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.7
  lottie: ^2.7.0
  pinput: ^4.0.0
  intl: ^0.19.0
  image_picker: ^1.0.5
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  internet_connection_checker: ^1.0.0+1
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.2
  dropdown_button2: ^2.3.9
  shimmer: ^3.0.0
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  mask_text_input_formatter: ^2.9.0

  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.2
  smooth_page_indicator: ^1.1.0
  animate_do: ^3.1.2

  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.9
  freezed: ^2.5.0
  hive_generator: ^2.0.1


flutter:

  uses-material-design: true

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf
        - asset: assets/fonts/Urbanist-Bold.ttf
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
        - asset: assets/fonts/Urbanist-Medium.ttf
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-Semibold.ttf
  assets:
    - assets/icons/
    - assets/
    - assets/l10n/
    - assets/fonts/
    - assets/images/
    - assets/images/avatars/



